env:
  browser: true
  es2021: true
extends:
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - 'import'
  - 'prefer-arrow'
root: true
rules:
  'prefer-arrow/prefer-arrow-functions':
    - 'error'
    - disallowPrototype: true
      singleReturnOnly: false
      classPropertiesAllowed: false
